// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BridgeError struct {
	_tab flatbuffers.Table
}

func GetRootAsBridgeError(buf []byte, offset flatbuffers.UOffsetT) *BridgeError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BridgeError{}
	x.Init(buf, n+offset)
	return x
}

func FinishBridgeErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBridgeError(buf []byte, offset flatbuffers.UOffsetT) *BridgeError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BridgeError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBridgeErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BridgeError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BridgeError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BridgeError) File() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BridgeError) Line() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BridgeError) MutateLine(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *BridgeError) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BridgeError) IsTypeError() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BridgeError) MutateIsTypeError(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func BridgeErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BridgeErrorAddFile(builder *flatbuffers.Builder, file flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(file), 0)
}
func BridgeErrorAddLine(builder *flatbuffers.Builder, line int32) {
	builder.PrependInt32Slot(1, line, 0)
}
func BridgeErrorAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func BridgeErrorAddIsTypeError(builder *flatbuffers.Builder, isTypeError bool) {
	builder.PrependBoolSlot(3, isTypeError, false)
}
func BridgeErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
