// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CallEdge struct {
	_tab flatbuffers.Table
}

func GetRootAsCallEdge(buf []byte, offset flatbuffers.UOffsetT) *CallEdge {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CallEdge{}
	x.Init(buf, n+offset)
	return x
}

func FinishCallEdgeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCallEdge(buf []byte, offset flatbuffers.UOffsetT) *CallEdge {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CallEdge{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCallEdgeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CallEdge) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CallEdge) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CallEdge) Caller() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CallEdge) Callee() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CallEdge) CallSite(obj *SourcePos) *SourcePos {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SourcePos)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *CallEdge) IsStatic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallEdge) MutateIsStatic(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *CallEdge) IsGo() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallEdge) MutateIsGo(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *CallEdge) IsDefer() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallEdge) MutateIsDefer(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func CallEdgeStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func CallEdgeAddCaller(builder *flatbuffers.Builder, caller flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(caller), 0)
}
func CallEdgeAddCallee(builder *flatbuffers.Builder, callee flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(callee), 0)
}
func CallEdgeAddCallSite(builder *flatbuffers.Builder, callSite flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(callSite), 0)
}
func CallEdgeAddIsStatic(builder *flatbuffers.Builder, isStatic bool) {
	builder.PrependBoolSlot(3, isStatic, false)
}
func CallEdgeAddIsGo(builder *flatbuffers.Builder, isGo bool) {
	builder.PrependBoolSlot(4, isGo, false)
}
func CallEdgeAddIsDefer(builder *flatbuffers.Builder, isDefer bool) {
	builder.PrependBoolSlot(5, isDefer, false)
}
func CallEdgeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
