// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CallGraph struct {
	_tab flatbuffers.Table
}

func GetRootAsCallGraph(buf []byte, offset flatbuffers.UOffsetT) *CallGraph {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CallGraph{}
	x.Init(buf, n+offset)
	return x
}

func FinishCallGraphBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCallGraph(buf []byte, offset flatbuffers.UOffsetT) *CallGraph {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CallGraph{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCallGraphBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CallGraph) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CallGraph) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CallGraph) Edges(obj *CallEdge, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CallGraph) EdgesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CallGraphStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CallGraphAddEdges(builder *flatbuffers.Builder, edges flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(edges), 0)
}
func CallGraphStartEdgesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CallGraphEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
