// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import "strconv"

type ChannelDir int8

const (
	ChannelDirSendRecv ChannelDir = 0
	ChannelDirSendOnly ChannelDir = 1
	ChannelDirRecvOnly ChannelDir = 2
)

var EnumNamesChannelDir = map[ChannelDir]string{
	ChannelDirSendRecv: "SendRecv",
	ChannelDirSendOnly: "SendOnly",
	ChannelDirRecvOnly: "RecvOnly",
}

var EnumValuesChannelDir = map[string]ChannelDir{
	"SendRecv": ChannelDirSendRecv,
	"SendOnly": ChannelDirSendOnly,
	"RecvOnly": ChannelDirRecvOnly,
}

func (v ChannelDir) String() string {
	if s, ok := EnumNamesChannelDir[v]; ok {
		return s
	}
	return "ChannelDir(" + strconv.FormatInt(int64(v), 10) + ")"
}
