// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeferInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsDeferInfo(buf []byte, offset flatbuffers.UOffsetT) *DeferInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeferInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeferInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeferInfo(buf []byte, offset flatbuffers.UOffsetT) *DeferInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeferInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeferInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeferInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeferInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeferInfo) CallTarget() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeferInfo) SourcePos(obj *SourcePos) *SourcePos {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SourcePos)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeferInfo) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeferInfo) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func DeferInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DeferInfoAddCallTarget(builder *flatbuffers.Builder, callTarget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(callTarget), 0)
}
func DeferInfoAddSourcePos(builder *flatbuffers.Builder, sourcePos flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sourcePos), 0)
}
func DeferInfoAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(2, index, 0)
}
func DeferInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
