// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import "strconv"

type InstructionKind int8

const (
	InstructionKindAlloc           InstructionKind = 0
	InstructionKindPhi             InstructionKind = 1
	InstructionKindCall            InstructionKind = 2
	InstructionKindBinOp           InstructionKind = 3
	InstructionKindUnOp            InstructionKind = 4
	InstructionKindConvert         InstructionKind = 5
	InstructionKindChangeType      InstructionKind = 6
	InstructionKindMakeInterface   InstructionKind = 7
	InstructionKindMakeSlice       InstructionKind = 8
	InstructionKindMakeMap         InstructionKind = 9
	InstructionKindMakeChan        InstructionKind = 10
	InstructionKindMakeClosure     InstructionKind = 11
	InstructionKindFieldAddr       InstructionKind = 12
	InstructionKindIndexAddr       InstructionKind = 13
	InstructionKindLookup          InstructionKind = 14
	InstructionKindMapLookup       InstructionKind = 15
	InstructionKindSlice           InstructionKind = 16
	InstructionKindIf              InstructionKind = 17
	InstructionKindJump            InstructionKind = 18
	InstructionKindReturn          InstructionKind = 19
	InstructionKindPanic           InstructionKind = 20
	InstructionKindGo              InstructionKind = 21
	InstructionKindDefer           InstructionKind = 22
	InstructionKindSelect          InstructionKind = 23
	InstructionKindSend            InstructionKind = 24
	InstructionKindTypeAssert      InstructionKind = 25
	InstructionKindChangeInterface InstructionKind = 26
	InstructionKindExtract         InstructionKind = 27
	InstructionKindNext            InstructionKind = 28
	InstructionKindRange           InstructionKind = 29
	InstructionKindStore           InstructionKind = 30
	InstructionKindLoad            InstructionKind = 31
	InstructionKindMapUpdate       InstructionKind = 32
	InstructionKindRunDefers       InstructionKind = 33
	InstructionKindUnknown         InstructionKind = 34
	InstructionKindFuncParam       InstructionKind = 35
)

var EnumNamesInstructionKind = map[InstructionKind]string{
	InstructionKindAlloc:           "Alloc",
	InstructionKindPhi:             "Phi",
	InstructionKindCall:            "Call",
	InstructionKindBinOp:           "BinOp",
	InstructionKindUnOp:            "UnOp",
	InstructionKindConvert:         "Convert",
	InstructionKindChangeType:      "ChangeType",
	InstructionKindMakeInterface:   "MakeInterface",
	InstructionKindMakeSlice:       "MakeSlice",
	InstructionKindMakeMap:         "MakeMap",
	InstructionKindMakeChan:        "MakeChan",
	InstructionKindMakeClosure:     "MakeClosure",
	InstructionKindFieldAddr:       "FieldAddr",
	InstructionKindIndexAddr:       "IndexAddr",
	InstructionKindLookup:          "Lookup",
	InstructionKindMapLookup:       "MapLookup",
	InstructionKindSlice:           "Slice",
	InstructionKindIf:              "If",
	InstructionKindJump:            "Jump",
	InstructionKindReturn:          "Return",
	InstructionKindPanic:           "Panic",
	InstructionKindGo:              "Go",
	InstructionKindDefer:           "Defer",
	InstructionKindSelect:          "Select",
	InstructionKindSend:            "Send",
	InstructionKindTypeAssert:      "TypeAssert",
	InstructionKindChangeInterface: "ChangeInterface",
	InstructionKindExtract:         "Extract",
	InstructionKindNext:            "Next",
	InstructionKindRange:           "Range",
	InstructionKindStore:           "Store",
	InstructionKindLoad:            "Load",
	InstructionKindMapUpdate:       "MapUpdate",
	InstructionKindRunDefers:       "RunDefers",
	InstructionKindUnknown:         "Unknown",
	InstructionKindFuncParam:       "FuncParam",
}

var EnumValuesInstructionKind = map[string]InstructionKind{
	"Alloc":           InstructionKindAlloc,
	"Phi":             InstructionKindPhi,
	"Call":            InstructionKindCall,
	"BinOp":           InstructionKindBinOp,
	"UnOp":            InstructionKindUnOp,
	"Convert":         InstructionKindConvert,
	"ChangeType":      InstructionKindChangeType,
	"MakeInterface":   InstructionKindMakeInterface,
	"MakeSlice":       InstructionKindMakeSlice,
	"MakeMap":         InstructionKindMakeMap,
	"MakeChan":        InstructionKindMakeChan,
	"MakeClosure":     InstructionKindMakeClosure,
	"FieldAddr":       InstructionKindFieldAddr,
	"IndexAddr":       InstructionKindIndexAddr,
	"Lookup":          InstructionKindLookup,
	"MapLookup":       InstructionKindMapLookup,
	"Slice":           InstructionKindSlice,
	"If":              InstructionKindIf,
	"Jump":            InstructionKindJump,
	"Return":          InstructionKindReturn,
	"Panic":           InstructionKindPanic,
	"Go":              InstructionKindGo,
	"Defer":           InstructionKindDefer,
	"Select":          InstructionKindSelect,
	"Send":            InstructionKindSend,
	"TypeAssert":      InstructionKindTypeAssert,
	"ChangeInterface": InstructionKindChangeInterface,
	"Extract":         InstructionKindExtract,
	"Next":            InstructionKindNext,
	"Range":           InstructionKindRange,
	"Store":           InstructionKindStore,
	"Load":            InstructionKindLoad,
	"MapUpdate":       InstructionKindMapUpdate,
	"RunDefers":       InstructionKindRunDefers,
	"Unknown":         InstructionKindUnknown,
	"FuncParam":       InstructionKindFuncParam,
}

func (v InstructionKind) String() string {
	if s, ok := EnumNamesInstructionKind[v]; ok {
		return s
	}
	return "InstructionKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
