// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Instruction struct {
	_tab flatbuffers.Table
}

func GetRootAsInstruction(buf []byte, offset flatbuffers.UOffsetT) *Instruction {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Instruction{}
	x.Init(buf, n+offset)
	return x
}

func FinishInstructionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInstruction(buf []byte, offset flatbuffers.UOffsetT) *Instruction {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Instruction{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInstructionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Instruction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Instruction) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Instruction) Kind() InstructionKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return InstructionKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Instruction) MutateKind(n InstructionKind) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Instruction) SourcePos(obj *SourcePos) *SourcePos {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SourcePos)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Instruction) ResultVar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) ResultType(obj *TypeInfo) *TypeInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Instruction) Operands(obj *Operand, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Instruction) OperandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Instruction) CallTarget() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) CallTargetQualified() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) IsInterfaceCall() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Instruction) MutateIsInterfaceCall(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *Instruction) FieldName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) MapKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) ChannelOp() ChannelDir {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return ChannelDir(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Instruction) MutateChannelOp(n ChannelDir) bool {
	return rcv._tab.MutateInt8Slot(24, int8(n))
}

func (rcv *Instruction) TypeAssertTarget() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Instruction) TypeAssertHasOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Instruction) MutateTypeAssertHasOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func (rcv *Instruction) SelectCases(obj *SelectCase, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Instruction) SelectCasesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Instruction) ExtractIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Instruction) MutateExtractIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(32, n)
}

func InstructionStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func InstructionAddKind(builder *flatbuffers.Builder, kind InstructionKind) {
	builder.PrependInt8Slot(0, int8(kind), 0)
}
func InstructionAddSourcePos(builder *flatbuffers.Builder, sourcePos flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sourcePos), 0)
}
func InstructionAddResultVar(builder *flatbuffers.Builder, resultVar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(resultVar), 0)
}
func InstructionAddResultType(builder *flatbuffers.Builder, resultType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(resultType), 0)
}
func InstructionAddOperands(builder *flatbuffers.Builder, operands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(operands), 0)
}
func InstructionStartOperandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InstructionAddCallTarget(builder *flatbuffers.Builder, callTarget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(callTarget), 0)
}
func InstructionAddCallTargetQualified(builder *flatbuffers.Builder, callTargetQualified flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(callTargetQualified), 0)
}
func InstructionAddIsInterfaceCall(builder *flatbuffers.Builder, isInterfaceCall bool) {
	builder.PrependBoolSlot(7, isInterfaceCall, false)
}
func InstructionAddFieldName(builder *flatbuffers.Builder, fieldName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(fieldName), 0)
}
func InstructionAddMapKey(builder *flatbuffers.Builder, mapKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(mapKey), 0)
}
func InstructionAddChannelOp(builder *flatbuffers.Builder, channelOp ChannelDir) {
	builder.PrependInt8Slot(10, int8(channelOp), 0)
}
func InstructionAddTypeAssertTarget(builder *flatbuffers.Builder, typeAssertTarget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(typeAssertTarget), 0)
}
func InstructionAddTypeAssertHasOk(builder *flatbuffers.Builder, typeAssertHasOk bool) {
	builder.PrependBoolSlot(12, typeAssertHasOk, false)
}
func InstructionAddSelectCases(builder *flatbuffers.Builder, selectCases flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(selectCases), 0)
}
func InstructionStartSelectCasesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InstructionAddExtractIndex(builder *flatbuffers.Builder, extractIndex int32) {
	builder.PrependInt32Slot(14, extractIndex, 0)
}
func InstructionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
