// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Operand struct {
	_tab flatbuffers.Table
}

func GetRootAsOperand(buf []byte, offset flatbuffers.UOffsetT) *Operand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Operand{}
	x.Init(buf, n+offset)
	return x
}

func FinishOperandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOperand(buf []byte, offset flatbuffers.UOffsetT) *Operand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Operand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOperandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Operand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Operand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Operand) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Operand) TypeInfo(obj *TypeInfo) *TypeInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Operand) IsConstant() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Operand) MutateIsConstant(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *Operand) ConstantValue() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Operand) IsNil() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Operand) MutateIsNil(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func OperandStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func OperandAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func OperandAddTypeInfo(builder *flatbuffers.Builder, typeInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typeInfo), 0)
}
func OperandAddIsConstant(builder *flatbuffers.Builder, isConstant bool) {
	builder.PrependBoolSlot(2, isConstant, false)
}
func OperandAddConstantValue(builder *flatbuffers.Builder, constantValue flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(constantValue), 0)
}
func OperandAddIsNil(builder *flatbuffers.Builder, isNil bool) {
	builder.PrependBoolSlot(4, isNil, false)
}
func OperandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
