// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Parameter struct {
	_tab flatbuffers.Table
}

func GetRootAsParameter(buf []byte, offset flatbuffers.UOffsetT) *Parameter {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Parameter{}
	x.Init(buf, n+offset)
	return x
}

func FinishParameterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsParameter(buf []byte, offset flatbuffers.UOffsetT) *Parameter {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Parameter{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedParameterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Parameter) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Parameter) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Parameter) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Parameter) TypeInfo(obj *TypeInfo) *TypeInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ParameterStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ParameterAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ParameterAddTypeInfo(builder *flatbuffers.Builder, typeInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typeInfo), 0)
}
func ParameterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
