// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReturnType struct {
	_tab flatbuffers.Table
}

func GetRootAsReturnType(buf []byte, offset flatbuffers.UOffsetT) *ReturnType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReturnType{}
	x.Init(buf, n+offset)
	return x
}

func FinishReturnTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReturnType(buf []byte, offset flatbuffers.UOffsetT) *ReturnType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReturnType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReturnTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReturnType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReturnType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReturnType) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReturnType) TypeInfo(obj *TypeInfo) *TypeInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ReturnTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReturnTypeAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ReturnTypeAddTypeInfo(builder *flatbuffers.Builder, typeInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typeInfo), 0)
}
func ReturnTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
