// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SelectCase struct {
	_tab flatbuffers.Table
}

func GetRootAsSelectCase(buf []byte, offset flatbuffers.UOffsetT) *SelectCase {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SelectCase{}
	x.Init(buf, n+offset)
	return x
}

func FinishSelectCaseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSelectCase(buf []byte, offset flatbuffers.UOffsetT) *SelectCase {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SelectCase{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSelectCaseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SelectCase) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SelectCase) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SelectCase) Dir() ChannelDir {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ChannelDir(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SelectCase) MutateDir(n ChannelDir) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *SelectCase) Channel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SelectCase) IsDefault() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SelectCase) MutateIsDefault(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func SelectCaseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SelectCaseAddDir(builder *flatbuffers.Builder, dir ChannelDir) {
	builder.PrependInt8Slot(0, int8(dir), 0)
}
func SelectCaseAddChannel(builder *flatbuffers.Builder, channel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(channel), 0)
}
func SelectCaseAddIsDefault(builder *flatbuffers.Builder, isDefault bool) {
	builder.PrependBoolSlot(2, isDefault, false)
}
func SelectCaseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
