// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SourcePos struct {
	_tab flatbuffers.Table
}

func GetRootAsSourcePos(buf []byte, offset flatbuffers.UOffsetT) *SourcePos {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SourcePos{}
	x.Init(buf, n+offset)
	return x
}

func FinishSourcePosBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSourcePos(buf []byte, offset flatbuffers.UOffsetT) *SourcePos {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SourcePos{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSourcePosBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SourcePos) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SourcePos) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SourcePos) File() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SourcePos) Line() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SourcePos) MutateLine(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *SourcePos) Column() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SourcePos) MutateColumn(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *SourcePos) EndLine() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SourcePos) MutateEndLine(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *SourcePos) EndColumn() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SourcePos) MutateEndColumn(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *SourcePos) Offset() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SourcePos) MutateOffset(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func SourcePosStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func SourcePosAddFile(builder *flatbuffers.Builder, file flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(file), 0)
}
func SourcePosAddLine(builder *flatbuffers.Builder, line int32) {
	builder.PrependInt32Slot(1, line, 0)
}
func SourcePosAddColumn(builder *flatbuffers.Builder, column int32) {
	builder.PrependInt32Slot(2, column, 0)
}
func SourcePosAddEndLine(builder *flatbuffers.Builder, endLine int32) {
	builder.PrependInt32Slot(3, endLine, 0)
}
func SourcePosAddEndColumn(builder *flatbuffers.Builder, endColumn int32) {
	builder.PrependInt32Slot(4, endColumn, 0)
}
func SourcePosAddOffset(builder *flatbuffers.Builder, offset int32) {
	builder.PrependInt32Slot(5, offset, 0)
}
func SourcePosEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
