// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsTypeInfo(buf []byte, offset flatbuffers.UOffsetT) *TypeInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypeInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishTypeInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTypeInfo(buf []byte, offset flatbuffers.UOffsetT) *TypeInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypeInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTypeInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TypeInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TypeInfo) Kind() TypeKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TypeKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TypeInfo) MutateKind(n TypeKind) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *TypeInfo) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeInfo) Underlying() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeInfo) IsPointer() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TypeInfo) MutateIsPointer(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *TypeInfo) IsInterface() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TypeInfo) MutateIsInterface(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *TypeInfo) IsError() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TypeInfo) MutateIsError(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *TypeInfo) IsChannel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TypeInfo) MutateIsChannel(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *TypeInfo) ChannelDir() ChannelDir {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return ChannelDir(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TypeInfo) MutateChannelDir(n ChannelDir) bool {
	return rcv._tab.MutateInt8Slot(18, int8(n))
}

func (rcv *TypeInfo) ElemType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeInfo) KeyType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TypeInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func TypeInfoAddKind(builder *flatbuffers.Builder, kind TypeKind) {
	builder.PrependInt8Slot(0, int8(kind), 0)
}
func TypeInfoAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func TypeInfoAddUnderlying(builder *flatbuffers.Builder, underlying flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(underlying), 0)
}
func TypeInfoAddIsPointer(builder *flatbuffers.Builder, isPointer bool) {
	builder.PrependBoolSlot(3, isPointer, false)
}
func TypeInfoAddIsInterface(builder *flatbuffers.Builder, isInterface bool) {
	builder.PrependBoolSlot(4, isInterface, false)
}
func TypeInfoAddIsError(builder *flatbuffers.Builder, isError bool) {
	builder.PrependBoolSlot(5, isError, false)
}
func TypeInfoAddIsChannel(builder *flatbuffers.Builder, isChannel bool) {
	builder.PrependBoolSlot(6, isChannel, false)
}
func TypeInfoAddChannelDir(builder *flatbuffers.Builder, channelDir ChannelDir) {
	builder.PrependInt8Slot(7, int8(channelDir), 0)
}
func TypeInfoAddElemType(builder *flatbuffers.Builder, elemType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(elemType), 0)
}
func TypeInfoAddKeyType(builder *flatbuffers.Builder, keyType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(keyType), 0)
}
func TypeInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
