// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import "strconv"

type TypeKind int8

const (
	TypeKindBasic     TypeKind = 0
	TypeKindPointer   TypeKind = 1
	TypeKindSlice     TypeKind = 2
	TypeKindMap       TypeKind = 3
	TypeKindChannel   TypeKind = 4
	TypeKindStruct    TypeKind = 5
	TypeKindInterface TypeKind = 6
	TypeKindFunction  TypeKind = 7
	TypeKindArray     TypeKind = 8
	TypeKindNamed     TypeKind = 9
	TypeKindTuple     TypeKind = 10
	TypeKindNil       TypeKind = 11
)

var EnumNamesTypeKind = map[TypeKind]string{
	TypeKindBasic:     "Basic",
	TypeKindPointer:   "Pointer",
	TypeKindSlice:     "Slice",
	TypeKindMap:       "Map",
	TypeKindChannel:   "Channel",
	TypeKindStruct:    "Struct",
	TypeKindInterface: "Interface",
	TypeKindFunction:  "Function",
	TypeKindArray:     "Array",
	TypeKindNamed:     "Named",
	TypeKindTuple:     "Tuple",
	TypeKindNil:       "Nil",
}

var EnumValuesTypeKind = map[string]TypeKind{
	"Basic":     TypeKindBasic,
	"Pointer":   TypeKindPointer,
	"Slice":     TypeKindSlice,
	"Map":       TypeKindMap,
	"Channel":   TypeKindChannel,
	"Struct":    TypeKindStruct,
	"Interface": TypeKindInterface,
	"Function":  TypeKindFunction,
	"Array":     TypeKindArray,
	"Named":     TypeKindNamed,
	"Tuple":     TypeKindTuple,
	"Nil":       TypeKindNil,
}

func (v TypeKind) String() string {
	if s, ok := EnumNamesTypeKind[v]; ok {
		return s
	}
	return "TypeKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
