// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ir

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Variable struct {
	_tab flatbuffers.Table
}

func GetRootAsVariable(buf []byte, offset flatbuffers.UOffsetT) *Variable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Variable{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariable(buf []byte, offset flatbuffers.UOffsetT) *Variable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Variable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Variable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Variable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Variable) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Variable) TypeInfo(obj *TypeInfo) *TypeInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Variable) SourcePos(obj *SourcePos) *SourcePos {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SourcePos)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func VariableStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func VariableAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func VariableAddTypeInfo(builder *flatbuffers.Builder, typeInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typeInfo), 0)
}
func VariableAddSourcePos(builder *flatbuffers.Builder, sourcePos flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sourcePos), 0)
}
func VariableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
